# Generated by Django 2.1 on 2019-09-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproducts',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активна'),
        ),
    ]
