# Generated by Django 2.1 on 2019-08-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mark',
            field=models.CharField(blank=True, max_length=128, verbose_name='маркер'),
        ),
    ]
